### PR TITLE
[Test PR] Checking if APK gets generated or not

### PR DESCRIPTION
**Pull request by sushant-varanasi**

### CODE REVIEW

**Comment by sushant-varanasi** [comment]
@JackMostow 
Sir, the APK doesn't get generated again. I'm examining what other issues might be the reason, as the ones Sanksar mentioned aren't the issues here.
Could you try generating a new GH token for Travis and send it to me. 
There was some confusion, as you mentioned in a previous mail, about 2 tokens.

**Review by JackMostow — DISMISSED** [review]
I emailed the second token.
What should I do about this PR?

- a. Nothing
- b. Merge it
- c. Close or cancel it
- d. Something else, namely what?

Thanks.  - Jack

**Comment by sushant-varanasi** [comment]
@JackMostow 
No APK had been generated on raising this PR with a test commit.
I'm not sure where the bug is exactly.
Yes, I received the email with GH token. I'll try encrypting it again and cross-check protocols from official docs.

a. Nothing - needs to be done from your side as of now.

Regards

**Review by JackMostow — DISMISSED** [review]
I don't know enough to understand the code changes, but I since they're newer than the original pull request, do you need to reissue it to make the new code generate an apk?

**Comment by sushant-varanasi** [comment]
Sir, I have been analysing the logs generated at [https://www.travis-ci.com/github/RoboTutorLLC/RoboFeel]
No need to merge the related new commits at the moment.

**Review by JackMostow — APPROVED** [review]
... except that evidently it didn't fix the problem  (:<).  I'll ask Sanskar what else to try.

**Comment by sushant-varanasi** [comment]
@JackMostow Just emailed you about the same haha

**Pull request merged**
