### PR TITLE
[In progress] encrypted gh token added

### PR DESCRIPTION
**Pull request by sushant-varanasi**
I have encrypted and added the gh token required in .travis.yml file. This must automatically create an apk now.

Addresses issue #3

### CODE REVIEW

**Review by JackMostow — APPROVED** [review]
Looks OK as far as I can tell.

**Comment by JackMostow** [comment]
> Looks OK as far as I can tell.

The apk branch doesn't yet show any apk generated, and this PR says "in progress".  When it's merged, will development branch PRs and merges automatically generate new apks?

**Comment by sushant-varanasi** [comment]
> > Looks OK as far as I can tell.
> 
> The apk branch doesn't yet show any apk generated, and this PR says "in progress". When it's merged, will development branch PRs and merges automatically generate new apks?

I remember Sanskar mentioning about APKs being generated as soon as PR gets raised.
But yes, you may merge this and let's check if APK gets generated. 
If it doesn't get generated, I'll work on what the new issue might be.

**Comment by JackMostow** [comment]
OK, I merged this PR as requested.  Please generate a PR for the development branch to see if an apk gets generated as we hope.

**Pull request merged**
